import { ArrowRight, ArrowUpRight, BarChart3, CalendarDays, Compass, House, Rocket, Store, Target, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { InfoSection } from './InfoSection';

export const AboutInformation = () => <>
  <InfoSection id="about" kicker="THE BIGGER PICTURE" title="About MART">
    <div className="mart-about-layout"><div className="mart-info-prose"><h3 data-testid="about-lead">MART is building a new layer around tokens.</h3><p>MART is a Solana token launchpad and token ecosystem platform. The idea is that a token should be more than something people simply trade.</p><p>Today, a token can have a chart, a social account, a community, and different activities spread across different platforms. MART brings these experiences together around the token itself.</p><p>It gives communities a place to trade, discover products, participate in events, and build activity around the token.</p><p className="mart-info-emphasis" data-testid="about-belief">Launching a token should be the beginning of something bigger.</p><Link to="/docs/what-is-mart" className="text-link" data-testid="about-read-docs">Get to know MART<ArrowUpRight size={15} /></Link></div><div className="mart-token-home" data-testid="about-token-home"><span className="mini-label">ONE TOKEN. EVERYTHING AROUND IT.</span>{[[House, 'A token gets a home.'], [BarChart3, 'A place to trade.'], [Store, 'A market.'], [CalendarDays, 'A place for events.'], [Users, 'A place for its community.']].map(([Icon, text], i) => <div key={text} data-testid={`token-home-purpose-${i}`}><span><Icon size={19} /></span><strong>{text}</strong><span className="mart-home-line" /></div>)}</div></div>
  </InfoSection>
  <div className="mart-purpose-grid">
    <section className="mart-info-panel" id="vision" aria-labelledby="vision-heading" data-testid="info-section-vision"><div className="mart-panel-overline"><Compass size={20} /><span className="eyebrow">THE WORLD WE SEE</span></div><h2 id="vision-heading" className="display-h2" data-testid="info-title-vision">Our Vision</h2><p>We believe tokens can become more than financial assets. They can become communities, cultures, brands, economies, and digital worlds.</p><p>MART’s vision is to make every token capable of building something around itself.</p><div className="mart-info-pullquote" data-testid="vision-principle"><span>The long-term idea is simple:</span><strong>Launching a token should only be the beginning.</strong></div></section>
    <section className="mart-info-panel" id="mission" aria-labelledby="mission-heading" data-testid="info-section-mission"><div className="mart-panel-overline"><Target size={20} /><span className="eyebrow">WHAT WE’RE BUILDING</span></div><h2 id="mission-heading" className="display-h2" data-testid="info-title-mission">Our Mission</h2><p>Build the infrastructure that helps token communities turn attention into activity.</p><p>MART brings trading, commerce, events, and community into one place around the token.</p><div className="mart-info-pullquote" data-testid="mission-principle"><span>The goal:</span><strong>A connected experience. Not a fragmented one.</strong></div></section>
  </div>
  <InfoSection id="mart-how-it-works" kicker="FROM AN IDEA TO AN ECOSYSTEM" title="How MART Works" intro="Start with a token. Give it a home. Build what comes next.">
    <div className="mart-steps-grid">{[[Rocket, '01', 'Launch', 'Create and launch a token through MART.'], [House, '02', 'Token Hub', 'The token gets its own Token Hub.'], [Store, '03', 'Build', 'The Token Hub brings together Trade · Market · Events · Community.'], [Users, '04', 'Grow', 'Creators, holders, traders, collectors, sellers, and communities can interact around the token.']].map(([Icon, number, title, copy]) => <article className="mart-info-panel mart-step-panel" key={number} data-testid={`how-step-${number}`}><div className="mart-step-top"><span className="mono">{number}</span><Icon size={20} /></div><h3>{title}</h3><p>{copy}</p><ArrowRight className="mart-step-arrow" size={15} /></article>)}</div><p className="mart-info-footnote">A new launch requires your wallet signature and network fees. <Link to="/docs/introduction" data-testid="how-it-works-guide">Read the practical guide<ArrowUpRight size={11} /></Link></p>
  </InfoSection>
</>;