import { Link } from 'react-router-dom';
import { ArrowUpRight, BarChart3, BellRing, Box, CalendarDays, Heart, Image, MessageCircle, MessagesSquare, Palette, Shirt, ShoppingBag, Store, Users } from 'lucide-react';
import { MARKET_CATEGORIES, EVENT_TYPES } from '../../content/mart';
import { InfoSection } from './InfoSection';

export const EcosystemInformation = () => <>
  <InfoSection id="token-hubs" kicker="ONE ADDRESS. A WHOLE ECOSYSTEM." title="The Token Hub" intro="Every token represented on MART has a central place for everything happening around it.">
    <div className="mart-hub-explanations">{[[BarChart3, 'Trade', 'Trade and follow the token.', 'Follow market data, explore the chart, and access available trading.'], [Store, 'Market', 'Buy and sell products using the token itself.', 'A marketplace that belongs to the token and the people around it.'], [CalendarDays, 'Events', 'Discover announcements and activities around the token.', 'A structured place for the community’s next big moment.'], [Users, 'Community', 'Talk, share, and interact with the token community.', 'Keep ideas, conversations, and creativity close to the token.']].map(([Icon, name, lead, text]) => <article className={`mart-info-panel mart-hub-feature ${name === 'Market' ? 'mart-feature-highlight' : ''}`} key={name} data-testid={`hub-explanation-${name.toLowerCase()}`}><span className="mart-feature-icon"><Icon size={22} /></span><h3>{name}</h3><strong>{lead}</strong><p>{text}</p></article>)}</div><Link className="text-link mart-under-link" to="/explore" data-testid="hub-explanation-explore">Find your Token Hub<ArrowUpRight size={15} /></Link>
  </InfoSection>
  <InfoSection id="markets" kicker="THE HEART OF MART" title="A Market Built Around the Token">
    <div className="mart-market-explanation"><div className="mart-info-prose"><h3>The Market is the core of MART.</h3><p>Every token can have its own marketplace. Products inside that Market are priced using the token itself.</p><p>This creates a marketplace directly around the token and its community. Not a global collection of unrelated products—a market with a shared identity and its own currency.</p><div className="mart-info-inline-note"><Store size={18} /><span>One token. One Market. The token is the payment currency.</span></div><Link to="/docs/markets" className="text-link" data-testid="market-explanation-guide">How token markets work<ArrowUpRight size={15} /></Link></div><div className="mart-price-example" data-testid="abc-market-example"><div className="mart-price-example-heading"><span><Store size={18} /><strong>$ABC Market</strong></span><span className="mini-label">ILLUSTRATIVE EXAMPLE</span></div>{[[Palette, 'Meme Pack', '10,000'], [Image, 'Poster', '25,000'], [Box, 'NFT', '100,000']].map(([Icon, name, price]) => <div className="mart-example-row" key={name} data-testid={`example-price-${name.toLowerCase().replaceAll(' ', '-')}`}><span className="mart-example-icon"><Icon size={17} /></span><span>{name}</span><strong>{price}<span> $ABC</span></strong></div>)}<p>Example prices only—not live listings. NFT sales are not currently enabled.</p></div></div>
    <h3 className="mart-categories-title" data-testid="market-category-heading">A place for different kinds of creation.</h3><div className="mart-category-explanations">{MARKET_CATEGORIES.map((category, i) => { const Icon = [Box, Palette, Shirt][i]; return <article className="mart-info-panel" data-testid={`market-category-info-${category.name.toLowerCase()}`} key={category.name}><div className="mart-category-heading"><Icon size={20} /><h4>{category.name}</h4></div><ul>{category.items.map(item => <li key={item}>{item}</li>)}</ul>{category.note && <p className="mart-category-note" data-testid="nft-availability-content">{category.note}</p>}</article>; })}</div>
  </InfoSection>
  <InfoSection id="token-events" kicker="GIVE YOUR COMMUNITY SOMETHING TO LOOK FORWARD TO" title="Events Around Every Token">
    <div className="mart-events-explanation"><div className="mart-info-prose"><p>Events give token communities a structured place to announce what is happening. Discover activities in a Token Hub or browse events across the MART ecosystem.</p><p>From a holder reward to an asset distribution, each announcement has a title, type, image, and description. Official events are managed by the verified token authority.</p><Link to="/events" className="text-link" data-testid="information-discover-events">Discover events<ArrowUpRight size={15} /></Link></div><div className="mart-event-types" data-testid="event-types-list">{EVENT_TYPES.map((type, i) => <span key={type} data-testid={`event-type-information-${i}`}><BellRing size={12} />{type}</span>)}</div></div><div className="mart-announcement-note" data-testid="information-event-disclaimer"><CalendarDays size={18} /><p><strong>Announcements, not guarantees.</strong> Events are announcements and community activity. MART does not guarantee that an announced event will be executed.</p></div>
  </InfoSection>
  <InfoSection id="community" kicker="THE PEOPLE MAKE THE TOKEN" title="A Place for the Community" intro="Every Token Hub has its own Community. A space for the people who make the token more than a ticker.">
    <div className="mart-community-explanation"><div className="mart-info-prose"><h3>Keep the conversation in one place.</h3><p>Share something you made. Discuss an upcoming event. Ask a question, exchange ideas, or just talk about the token.</p><p>The goal is to keep the conversation around the token in one place, so people can follow and contribute to the same community.</p><Link to="/explore" className="text-link" data-testid="information-find-community">Find your community<ArrowUpRight size={15} /></Link></div><div className="mart-community-actions" data-testid="community-capabilities">{[[MessageCircle, 'Post'], [Image, 'Share images'], [MessagesSquare, 'Reply'], [Heart, 'Like'], [CalendarDays, 'Discuss events'], [Palette, 'Share artwork'], [Users, 'Talk about the token']].map(([Icon, text]) => <span key={text}><Icon size={17} />{text}</span>)}</div></div>
  </InfoSection>
</>;