import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BadgeCheck, Circle, Compass, Plus, ShieldCheck, Sprout } from 'lucide-react';
import { FUTURE_DIRECTIONS } from '../../content/mart';
import { openAddToken } from '../../lib/navigation';
import { InfoSection } from './InfoSection';

export const ParticipationInformation = () => <>
  <InfoSection id="existing-token" kicker="YOUR STORY MAY HAVE ALREADY STARTED" title="Already Have a Token?">
    <div className="mart-existing-intro"><div className="mart-info-prose"><p>MART is not limited to tokens launched directly on MART. Any compatible Solana token can be added.</p><p>Existing tokens can become part of MART without needing to launch again. Bring the mint address. Build on what already exists.</p></div><button className="btn btn-primary" data-testid="information-add-token" onClick={openAddToken}><Plus size={16} />Add your token</button></div><ol className="mart-add-token-flow" data-testid="existing-token-flow">{['Paste Token Address', 'Fetch Token Information', 'Create Token Hub', 'Trade · Market · Events · Community'].map((step, i) => <li key={step}><span className="mono">0{i + 1}</span><strong>{step}</strong>{i < 3 && <ArrowRight size={16} />}</li>)}</ol><p className="mart-info-footnote">One address → one Token Hub. If the Hub already exists, MART opens it instead of creating a duplicate.</p>
  </InfoSection>
  <InfoSection id="verification" kicker="COMMUNITY PARTICIPATION. OFFICIAL IDENTITY." title="Unclaimed & Verified Tokens" intro="An existing token added to MART initially appears as Unclaimed. Adding a token does not automatically make the person who added it the official owner.">
    <div className="mart-verification-grid"><article className="mart-info-panel" data-testid="unclaimed-explanation"><div className="mart-status-label"><Circle size={17} /><span>UNCLAIMED</span></div><h3>Community-created Token Hub.</h3><p>A home started by the community. Supported listings and conversations can begin without granting anyone official control of the project.</p></article><article className="mart-info-panel mart-feature-highlight" data-testid="verified-explanation"><div className="mart-status-label"><BadgeCheck size={19} /><span>VERIFIED</span></div><h3>Officially claimed and verified.</h3><p>The legitimate project or verifiable token authority can claim its Hub and manage official information and events through the supported verification process.</p></article></div><div className="mart-verification-footer"><p>This lets communities start building while keeping official ownership separate. Verification is not an investment endorsement or a guarantee of safety.</p><Link to="/docs/token-verification" className="text-link" data-testid="verification-read-guide">Understand verification<ArrowUpRight size={14} /></Link></div>
  </InfoSection>
  <InfoSection id="why-mart" kicker="THE LAUNCH IS NOT THE FINISH LINE" title="Why MART?">
    <div className="mart-why-layout"><div className="mart-info-prose"><p>Most token platforms focus primarily on launching and trading. MART goes further.</p><p>The goal is to give tokens more places to create activity and value around themselves.</p><h3 className="mart-why-statement" data-testid="why-mart-statement">MART is not just where a token starts.<br /><span>It is where the token can build what comes next.</span></h3></div><div className="mart-why-path" data-testid="mart-ecosystem-path">{['Launch', 'Trade', 'Market', 'Events', 'Community'].map((name, i) => <div key={name}><span className="mono">0{i + 1}</span><strong>{name}</strong><span className={name === 'Market' ? 'live-dot' : 'mart-path-dot'} /></div>)}</div></div>
  </InfoSection>
  <InfoSection id="future" kicker="A DIRECTION. NOT A DATED ROADMAP." title="Where MART Is Going" intro="MART is starting with the foundation for a larger token economy. Future development can expand into:">
    <div className="mart-future-directions" data-testid="future-directions">{FUTURE_DIRECTIONS.map((direction, i) => <div key={direction}><span className="mono">0{i + 1}</span><span>{direction}</span><ArrowUpRight size={14} /></div>)}</div><div className="mart-future-note"><Sprout size={18} /><p>These are long-term directions for MART, not release dates, delivery commitments, or promises of financial value.</p></div>
  </InfoSection>
</>;