import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Activity, Check, Clock3, Loader2, FileText, ChevronDown, ExternalLink, Download, CircleAlert } from 'lucide-react';
import { Modal } from '../Kit';

const labels = { queued: 'Dalam antrean', running: 'Menyusun riset', completed: 'Selesai', failed: 'Gagal', rejected: 'Tidak dijalankan' };
export const ResearchActivity = ({ data, token }) => {
  const [tab, setTab] = useState('activity'), [selected, setSelected] = useState(null);
  const active = data?.runs.find(r => r.id === selected);
  const exportReport = run => { const file = new Blob([`# ${token.name} — Riset agent\n\nModel: ${run.model_id}\nTanggal: ${run.created_at}\n\n${run.output}`], { type: 'text/markdown;charset=utf-8' }); const url = URL.createObjectURL(file); const a = document.createElement('a'); a.href = url; a.download = `${token.symbol}-research-${run.id.slice(0, 8)}.md`; a.click(); URL.revokeObjectURL(url); };
  return <section className="research-activity" data-testid="hub-activity-log-container">
    <div className="compute-section-heading"><div><span className="compute-eyebrow"><Activity size={14} />JEJAK EKSEKUSI</span><h2 data-testid="research-activity-title">Aktivitas agent<span>.</span></h2></div><span className="compute-live-label" data-testid="research-live-status"><i className={data?.active_run ? 'pulsing' : ''} />{data?.active_run ? 'BERJALAN' : 'TERCATAT'}</span></div>
    <div className="research-tabs" role="tablist" aria-label="Aktivitas agent">{[['activity', 'Activity log'], ['reports', 'Hasil riset'], ['usage', 'Penggunaan']].map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} onClick={() => setTab(key)} className={tab === key ? 'active' : ''} data-testid={`research-tab-${key}`}>{label}{key === 'reports' && <span>{data?.runs.filter(r => r.status === 'completed').length || 0}</span>}</button>)}</div>
    <div className="research-tab-content" role="tabpanel" data-testid={`research-panel-${tab}`}>
      {tab === 'activity' && (data?.activity.length ? <div className="research-timeline">{data.activity.slice(0, 10).map(item => <div className={`research-log ${item.kind}`} key={item.id} data-testid={`activity-event-${item.id}`}><span className="log-event-icon">{item.kind === 'completed' ? <Check size={13} /> : item.kind === 'failed' ? <CircleAlert size={13} /> : <Activity size={13} />}</span><div><strong data-testid={`activity-title-${item.id}`}>{item.title}</strong><span data-testid={`activity-meta-${item.id}`}>{item.kind.toUpperCase()}{item.run_id && ` · #${item.run_id.slice(0, 8)}`}</span></div><time data-testid={`activity-time-${item.id}`}>{new Date(item.at).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}</time></div>)}</div> : <div className="research-empty" data-testid="research-activity-empty"><Activity size={26} /><strong>Belum ada aktivitas</strong><p>Catatan eksekusi {token.symbol} akan muncul di sini.</p></div>)}
      {tab === 'reports' && (data?.runs.length ? data.runs.map(run => <button className="research-report-row" key={run.id} data-testid={`research-report-${run.id}`} onClick={() => setSelected(run.id)}><FileText size={19} /><span><strong data-testid={`research-report-title-${run.id}`}>Riset {token.symbol} <small>{run.trigger === 'manual' ? 'MANUAL' : 'TERJADWAL'}</small></strong><span>{new Date(run.created_at).toLocaleString('id-ID')} · {run.model_id}</span></span><span className={`research-run-status ${run.status}`} data-testid={`research-status-${run.id}`}>{run.status === 'running' && <Loader2 size={12} className="spin" />}{labels[run.status]}</span><ChevronDown size={14} /></button>) : <div className="research-empty" data-testid="research-reports-empty"><FileText size={26} /><strong>Riset pertama menanti</strong><p>Hasil dan ide event tersimpan untuk token ini.</p></div>)}
      {tab === 'usage' && <div className="compute-ledger">{!data?.ledger.length ? <div className="research-empty" data-testid="compute-ledger-empty"><Clock3 size={26} /><strong>Belum ada penggunaan kredit</strong></div> : data.ledger.slice(0, 20).map(item => <div className="ledger-row" data-testid={`ledger-${item.id}`} key={item.id}><div><strong>{item.kind === 'topup' ? 'Pengisian kredit uji' : item.kind === 'usage' ? 'Biaya riset' : 'Reservasi dikembalikan'}</strong><span>{new Date(item.at).toLocaleString('id-ID')}{item.model_id && ` · ${item.model_id}`}</span>{item.usage?.total_tokens > 0 && <span data-testid={`ledger-tokens-${item.id}`}>{item.usage.input_tokens} masuk / {item.usage.output_tokens} keluar · alat 0 CR</span>}{item.released > 0 && <span data-testid={`ledger-release-${item.id}`}>Sisa reservasi: {item.released.toFixed(4)} CR dikembalikan</span>}</div><strong className={item.amount >= 0 ? 'positive' : ''} data-testid={`ledger-amount-${item.id}`}>{item.amount >= 0 ? '+' : ''}{item.amount.toFixed(4)} CR</strong></div>)}</div>}
    </div>
    {data?.active_run && <button className="research-running" data-testid="research-view-running" onClick={() => setSelected(data.active_run)}><Loader2 size={14} className="spin" />Lihat riset yang sedang berjalan<ExternalLink size={13} /></button>}
    <Modal open={!!selected} onClose={() => setSelected(null)} id="research-report" title={`Riset ${token.symbol}`} description={active ? `${active.model_id} · ${labels[active.status]} · #${active.id.slice(0, 8)}` : 'Memuat laporan…'}>
      {active?.usage?.finish_reason === 'length' && <p className="compute-warning" role="status" data-testid="research-output-limit-notice">Batas output tercapai. Laporan ini parsial; hanya token yang digunakan yang dihitung. Tidak ada kelanjutan otomatis yang menambah biaya.</p>}
      {active && <><div className="report-receipt" data-testid="research-report-receipt"><span>{(active.charged / 1000000).toFixed(4)} CR terpakai</span><span>{active.usage?.total_tokens || '—'} token</span><span>Draft · bukan nasihat keuangan</span></div>{active.error && <p role="alert" className="compute-warning" data-testid="research-report-error">{active.error}</p>}<div className="research-markdown" data-testid="research-report-output"><ReactMarkdown components={{ a: ({ node, ...props }) => <a {...props} data-testid={`research-inline-link-${node.position?.start.offset}`} target="_blank" rel="noreferrer" /> }}>{active.output || 'Mengumpulkan data token dan menyiapkan riset…'}</ReactMarkdown>{active.status === 'running' && <Loader2 className="spin" size={16} />}</div><div className="report-sources" data-testid="research-report-sources">{active.sources?.map((source, i) => <a href={source.url} target="_blank" rel="noreferrer" data-testid={`research-source-${i}`} key={source.url}>{source.label}<ExternalLink size={12} /></a>)}</div>{active.status === 'completed' && <button className="btn btn-secondary" data-testid="research-export" onClick={() => exportReport(active)}><Download size={14} />Unduh laporan</button>}</>}
    </Modal>
  </section>;
};