import { useState } from 'react';
import { Heart, MessageCircle, Send, ImagePlus, Users, ArrowUpRight } from 'lucide-react';
import { toast } from 'sonner';
import { api, useData, short } from '../lib/api';
import { Btn, Field, UploadImage, Empty, Loading, ErrorBox } from '../components/Kit';
import { useWallet } from '../components/WalletContext';

const Post = ({ post, reload }) => {
  const { wallet, requireWallet } = useWallet(); const [replyOpen, setReplyOpen] = useState(false), [reply, setReply] = useState(''), [busy, setBusy] = useState(false);
  async function like() { if (!requireWallet()) return; try { await api(`/posts/${post.id}/like`, { method: 'POST' }); reload(); } catch(e) { toast.error(e.message); } }
  async function send(e) { e.preventDefault(); if (!requireWallet()) return; setBusy(true); try { await api(`/posts/${post.id}/replies`, { method: 'POST', body: { text: reply } }); setReply(''); reload(); } catch(e) { toast.error(e.message); } finally { setBusy(false); } }
  return <article className="post" data-testid={`community-post-${post.id}`}><div className="post-heading"><span className="user-avatar">{post.author.slice(0, 2)}</span><div><strong>{short(post.author)}</strong><span>{new Date(post.created_at).toLocaleString()}</span></div></div><p className="post-text" data-testid={`post-text-${post.id}`}>{post.text}</p>{post.image && <img className="post-image" src={post.image} alt="Community post attachment" />}<div className="post-actions"><button className={post.likes.includes(wallet) ? 'liked' : ''} data-testid={`like-post-${post.id}`} onClick={like}><Heart size={16} fill={post.likes.includes(wallet) ? 'currentColor' : 'none'} />{post.likes.length}</button><button data-testid={`reply-post-${post.id}`} onClick={() => setReplyOpen(!replyOpen)}><MessageCircle size={16} />{post.replies.length} replies</button></div>{replyOpen && <div className="replies">{post.replies.map(r => <div className="reply" data-testid={`reply-${r.id}`} key={r.id}><strong>{short(r.author)}</strong><p>{r.text}</p></div>)}<form className="reply-form" onSubmit={send}><input data-testid={`reply-input-${post.id}`} aria-label="Your reply" placeholder="Add to the conversation…" required maxLength={2000} value={reply} onChange={e => setReply(e.target.value)} /><Btn data-testid={`send-reply-${post.id}`} type="submit" busy={busy} aria-label="Send reply"><Send size={15} /></Btn></form></div>}</article>;
};

export default function Community({ token }) {
  const { wallet, requireWallet, openWallet } = useWallet(); const { data, loading, error, reload } = useData(`/tokens/${token.address}/posts`);
  const [text, setText] = useState(''), [image, setImage] = useState(''), [upload, setUpload] = useState(false), [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); if (!requireWallet()) return; setBusy(true); try { await api(`/tokens/${token.address}/posts`, { method: 'POST', body: { text, image } }); setText(''); setImage(''); setUpload(false); toast.success('Posted to your community.'); reload(); } catch(e) { toast.error(e.message); } finally { setBusy(false); } }
  return <div className="community-layout"><div><div className="section-heading"><div><span className="eyebrow">THE PEOPLE BEHIND THE TOKEN</span><h2 className="display-h2" data-testid="community-title">${token.symbol} Community</h2></div></div><form className="post-composer" onSubmit={submit}><textarea data-testid="community-post-input" placeholder={`What’s happening in the $${token.symbol} world?`} maxLength={2000} required value={text} onChange={e => setText(e.target.value)} aria-label="Create a community post" />{upload && <UploadImage id="community-image" value={image} onChange={setImage} />}<div><button type="button" data-testid="attach-post-image" className="text-link" onClick={() => { if (requireWallet()) setUpload(!upload); }}><ImagePlus size={18} />Add image</button><Btn type={wallet ? 'submit' : 'button'} data-testid="submit-community-post" busy={busy} onClick={wallet ? undefined : openWallet}>{wallet ? 'Post' : 'Connect to post'}<ArrowUpRight size={15} /></Btn></div></form>{loading ? <Loading /> : error ? <ErrorBox error={error} /> : data?.length ? data.map(p => <Post key={p.id} post={p} reload={reload} />) : <Empty icon={MessageCircle} title="Every community starts with a conversation." text="Share an idea, drop a meme, or just say hello. This space belongs to your token." />}</div><aside className="community-aside"><span className="empty-icon"><Users size={24} /></span><h3>More than holders.<br />A community.</h3><p>This is the home for everyone building around ${token.symbol}.</p><div className="aside-rule" /><h4>Keep it good.</h4><p>Be respectful. Share original work. Never post seed phrases or private keys.</p><span className="small-text muted">Community posts are not official token announcements.</span></aside></div>;
}