import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CalendarDays, ArrowUpRight, Plus, Radio, ArrowLeft, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { api, useData } from '../lib/api';
import { Btn, Modal, Field, Choice, UploadImage, Empty, Loading, ErrorBox, TokenAvatar } from '../components/Kit';
import { useWallet } from '../components/WalletContext';
import { ManageEvent } from '../components/OfficialTools';

const TYPES = ['Holder Reward', 'Airdrop', 'Buyback', 'Burn', 'LP Action', 'NFT / Asset Distribution', 'Other'];
export const EventTicker = ({ token }) => {
  const { data } = useData(`/events?token=${token.address}`);
  const active = data?.filter(e => e.status !== 'past') || [];
  return <div className="event-ticker" data-testid="token-event-ticker"><span className="ticker-label"><Radio size={14} />HUB SIGNAL</span><div className="ticker-window">{active.length ? <div className="ticker-track">{[...active, ...active].map((e, i) => <Link data-testid={`ticker-event-${i}`} to={`/events/${e.id}`} key={`${e.id}-${i}`}><span className="live-dot" /><strong>{e.status === 'live' ? 'LIVE' : 'UPCOMING'}</strong>{e.title}<ArrowUpRight size={12} /></Link>)}</div> : <span className="ticker-empty" data-testid="ticker-no-events">Your community’s next big moment starts here. <Link to={`/token/${token.address}/events`} data-testid="ticker-view-events">Explore events<ArrowUpRight size={13} /></Link></span>}</div></div>;
};
const EventCard = ({ event }) => <Link className="event-card" to={`/events/${event.id}`} data-testid={`event-card-${event.id}`}><div className="event-image">{event.image ? <img src={event.image} alt={event.title} /> : <CalendarDays size={52} />}<span className={`event-status ${event.status}`}><span className="live-dot" />{event.status === 'upcoming' ? 'COMING SOON' : event.status.toUpperCase()}</span></div><div className="event-card-content"><span className="eyebrow">{event.type}</span><h3>{event.title}</h3><p>{event.description}</p><div><TokenAvatar small token={{ logo: event.token_logo, symbol: event.symbol }} /><strong>${event.symbol}</strong><ArrowUpRight size={18} /></div></div></Link>;
const EventForm = ({ token, close, refresh }) => {
  const [form, setForm] = useState({ title: '', image: '', type: TYPES[0], description: '', status: 'upcoming' }), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { await api(`/tokens/${token.address}/events`, { method: 'POST', body: form }); toast.success('Event published to your Token Hub.'); close(); refresh(); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <form className="form-stack" onSubmit={submit}><Field id="event-title" label="Event title" required minLength={3} maxLength={120} value={form.title} onChange={e => set('title', e.target.value)} placeholder="Give your community something to look forward to" /><UploadImage id="event-image" value={form.image} onChange={v => set('image', v)} label="Upload event image" /><div className="form-row"><Choice id="event-type" label="Event type" options={TYPES} value={form.type} onChange={v => set('type', v)} /><Choice id="event-status" label="Status" options={[{ value: 'upcoming', label: 'Coming Soon' }, { value: 'live', label: 'Live' }, { value: 'past', label: 'Past' }]} value={form.status} onChange={v => set('status', v)} /></div><Field textarea id="event-description" label="Description" minLength={10} maxLength={5000} required value={form.description} onChange={e => set('description', e.target.value)} placeholder="What’s happening? Include timing and participation details." /><div className="info-note"><ShieldCheck size={18} /><p>Events are announcements, not guaranteed executions or commitments of funds.</p></div><ErrorBox error={error} /><Btn data-testid="create-event-submit" type="submit" busy={busy}>Create Event<ArrowUpRight size={16} /></Btn></form>;
};
const EventList = ({ token }) => {
  const [status, setStatus] = useState('live'), [open, setOpen] = useState(false); const { wallet, requireWallet } = useWallet();
  const { data, loading, error, reload } = useData(`/events?status=${status}${token ? `&token=${token.address}` : ''}`);
  function create() { if (!requireWallet()) return; if (token.claimed_by !== wallet) { toast.error('Only the verified token authority can publish official events. Use Claim this Token first.'); return; } setOpen(true); }
  return <><div className="section-heading">{token ? <div><span className="eyebrow">WHAT’S NEXT FOR YOUR TOKEN</span><h2 className="display-h2" data-testid="hub-events-title">${token.symbol} Events</h2><p>Big moments. Community first.</p></div> : <div className="page-heading"><span className="eyebrow">THE ECOSYSTEM NEVER STANDS STILL</span><h1 data-testid="events-title">Be part of what’s next<span className="green">.</span></h1><p>Discover drops, rewards, and community moments across MART.</p></div>}{token && <Btn data-testid="create-event-button" onClick={create}><Plus size={16} />Create Event</Btn>}</div><div className="filter-bar"><div className="pills">{[['live', 'Live'], ['upcoming', 'Coming Soon'], ['past', 'Past']].map(([v, label]) => <button data-testid={`events-filter-${v}`} className={status === v ? 'active' : ''} onClick={() => setStatus(v)} key={v}>{v === 'live' && <span className="live-dot" />}{label}</button>)}</div><span className="small-text muted" data-testid="events-count">{data?.length || 0} events</span></div>{loading ? <Loading /> : error ? <ErrorBox error={error} /> : data?.length ? <div className="event-grid">{data.map(e => <EventCard event={e} key={e.id} />)}</div> : <Empty icon={CalendarDays} title={status === 'live' ? 'The next big moment is coming.' : status === 'upcoming' ? 'Nothing on the calendar. Yet.' : 'A new chapter starts here.'} text={token ? 'Official events will appear here when the verified token team publishes them.' : 'Discover Token Hubs and their communities while you wait for the next event.'}>{!token && <Link className="btn btn-secondary" to="/explore" data-testid="events-explore-tokens">Explore Token Hubs<ArrowUpRight size={16} /></Link>}</Empty>}<p className="events-disclaimer" data-testid="events-disclaimer">Events are community announcements. MART does not guarantee execution, airdrops, rewards, or returns.</p>{token && <Modal open={open} onClose={() => setOpen(false)} title="Create an event" description={`An official announcement for the $${token.symbol} community.`} id="event"><EventForm token={token} close={() => setOpen(false)} refresh={reload} /></Modal>}</>;
};
export const HubEvents = ({ token }) => <EventList token={token} />;
export default function Events() { return <main className="container page"><EventList /></main>; }
export const EventDetail = () => {
  const { id } = useParams(); const { data: event, loading, error, reload } = useData(`/events/${id}`);
  return <main className="container page narrow-page"><Link className="text-link" to="/events" data-testid="event-back"><ArrowLeft size={15} />All events</Link>{loading ? <Loading /> : error ? <ErrorBox error={error} /> : <article className="event-detail" data-testid="event-detail">{event.image && <img src={event.image} alt={event.title} />}<span className="eyebrow">{event.type} / {event.status}</span><h1 data-testid="event-detail-title">{event.title}</h1><p className="preserve-text" data-testid="event-detail-description">{event.description}</p><Link className="btn btn-primary" to={`/token/${event.token}/events`} data-testid="event-open-hub">Open ${event.symbol} Token Hub<ArrowUpRight size={16} /></Link><ManageEvent event={event} reload={reload} /><p className="events-disclaimer">This announcement is not a guarantee of execution, distribution, or returns.</p></article>}</main>;
};