import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Rocket, ShoppingBag, Shapes, Users, Zap, Box, Sparkles, ShieldCheck, Circle, MoveUpRight } from 'lucide-react';
import { useData, ART, SHAPES, HOODIE } from '../lib/api';
import { TokenCard } from '../components/TokenCard';
import { Loading, ErrorBox } from '../components/Kit';
import { TokenHubPreview } from '../components/TokenHubPreview';
import { MartInformation } from '../components/information/MartInformation';
import { AgentLanding } from '../components/agent/AgentLanding';

export default function Home() {
  const { data: tokens, loading, error } = useData('/tokens');
  return <><div className="network-strip"><div><span className="live-dot" /><span>THE NEXT CHAPTER OF YOUR TOKEN</span><span className="strip-divider" /><span className="strip-copy">Your token. Your community. Your world on MART.</span><Link to="/explore" data-testid="strip-explore">Discover the ecosystem<ArrowUpRight size={13} /></Link></div></div><main className="container home">
    <section className="hero"><div className="hero-copy"><div className="eyebrow" data-testid="hero-eyebrow"><span className="live-dot" />MORE THAN A TOKEN. AN ENTIRE ECOSYSTEM.</div><h1 data-testid="hero-title">A market built<br />around <span>every<br className="hero-line" /> token.</span><span className="headline-star">✳</span></h1><p data-testid="hero-description">Launch your token. Build your market on MART.<br />Give your token a place to trade, create, and belong.</p><div className="hero-ctas"><Link className="btn btn-primary large" to="/launch" data-testid="hero-launch">Launch Token<ArrowUpRight size={18} /></Link><Link className="btn btn-secondary large" to="/explore" data-testid="hero-explore">Explore MART<ArrowRight size={18} /></Link></div><div className="hero-proof"><span className="solana-bars"><i /><i /><i /></span><span>Built on Solana</span><span className="proof-separator" /><ShieldCheck size={14} /><span>Your wallet. Your assets.</span></div></div><TokenHubPreview tokens={tokens} /></section>
    <section className="ecosystem-flow" id="how-it-works" data-testid="ecosystem-flow"><div className="flow-intro"><span className="mini-label">THE MART EFFECT</span><strong>One token.<br />A whole new world.</strong></div>{[[Rocket, '01', 'Launch your token', 'The beginning of your ecosystem.'], [Box, '02', 'Get your Token Hub', 'Your token’s home, automatically.'], [ShoppingBag, '03', 'Build your market', 'Trade. Create. Connect.']].map(([Icon, number, title, desc], i) => <div className="flow-step" key={number}><span className="flow-icon"><Icon size={22} /></span><div><span className="step-number">{number}</span><strong>{title}</strong><p>{desc}</p></div>{i < 2 && <ArrowRight className="flow-arrow" size={18} />}</div>)}</section>
    <AgentLanding />
    <section className="section-block"><div className="section-heading"><div><span className="eyebrow">FIND YOUR PEOPLE. FIND YOUR MARKET.</span><h2 className="display-h2" data-testid="featured-title">Tokens with a world of their own<span className="green">.</span></h2></div><Link className="text-link" to="/explore" data-testid="view-all-tokens">Explore all tokens<ArrowUpRight size={17} /></Link></div><div className="section-toolbar"><span className="selected-tab"><Zap size={14} />Featured hubs</span><span className="data-source"><span className="live-dot" />Market data by DexScreener</span></div>{loading ? <Loading /> : error ? <ErrorBox error={error} /> : <div className="token-grid">{tokens?.slice(0, 4).map((t, i) => <TokenCard token={t} index={i} key={t.address} />)}</div>}</section>
    <section className="section-block possibilities"><div className="section-heading"><div><span className="eyebrow">THE MARKET IS JUST THE BEGINNING</span><h2 className="display-h2" data-testid="market-possibilities-title">Culture, with its own currency.</h2></div><p>Not one marketplace for every token.<br />A world of possibilities for yours.</p></div><div className="category-grid">{[[ART, '01 / DIGITAL', 'Collect the unexpected.', 'NFTs & digital collectibles', Box], [SHAPES, '02 / ARTWORK', 'Make a little noise.', 'Art, meme packs & more', Shapes], [HOODIE, '03 / PHYSICAL', 'Take it into the real world.', 'Merch made for your community', ShoppingBag]].map(([img, label, title, subtitle, Icon], i) => <Link to="/explore" className="category-card" data-testid={`category-preview-${i}`} key={title}><img src={img} alt={subtitle} loading="lazy" /><div className="category-shade" /><span className="category-overline">{label}<Icon size={18} /></span><div className="category-copy"><h3>{title}</h3><p>{subtitle}</p><span className="category-arrow"><ArrowUpRight size={20} /></span></div></Link>)}</div><p className="concept-note" data-testid="concept-disclaimer">Market concepts shown for inspiration. Discover available listings inside each Token Hub.</p></section>
    <MartInformation />
    <section className="bottom-cta"><div className="cta-symbol"><Users size={36} /></div><div><span className="eyebrow">YOUR TOKEN HAS A FUTURE. BUILD IT HERE.</span><h2 className="display-h2">From a launch to a living ecosystem.</h2><p>The token is only the beginning. The rest is yours to create.</p></div><Link to="/launch" className="btn btn-primary large" data-testid="bottom-launch">Build your MART<ArrowUpRight size={18} /></Link></section>
  </main></>;
}