import { useState } from 'react';
import { ShoppingBag, Plus, ArrowUpRight, ShieldCheck, LockKeyhole, Package, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Buffer } from 'buffer';
import { api, useData, short, slug } from '../lib/api';
import { Btn, Modal, Field, Choice, UploadImage, Empty, Loading, ErrorBox } from '../components/Kit';
import { useWallet } from '../components/WalletContext';

const TYPES = ['Artwork', 'Meme Pack', 'Wallpaper', 'GIF', 'T-shirt', 'Hoodie', 'Poster', 'Sticker', 'Existing NFT', 'Create NFT'];
const initial = { name: '', image: '', type: 'Artwork', description: '', price: '', quantity: 1 };
const ListingForm = ({ token, close, refresh }) => {
  const [form, setForm] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState(''); const { wallet } = useWallet();
  const set = (key, value) => setForm(f => ({ ...f, [key]: value })); const nft = form.type.includes('NFT');
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { await api(`/tokens/${token.address}/listings`, { method: 'POST', body: { ...form, quantity: Number(form.quantity) } }); toast.success('Your listing is live in this Token Market.'); close(); refresh(); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <form className="form-stack" onSubmit={submit}><Choice id="listing-type" label="Item type" value={form.type} onChange={v => set('type', v)} options={TYPES} />{nft && <div className="info-note warning" data-testid="nft-availability-notice"><LockKeyhole size={19} /><p>{form.type === 'Existing NFT' ? 'NFT sales need verified ownership and an atomic exchange configuration. Listing is not enabled yet; your NFT stays in your wallet.' : 'NFT creation needs durable artwork storage and seller-funded minting. Minting is not enabled until those services are configured.'}</p></div>}<UploadImage id="listing-image" value={form.image} onChange={v => set('image', v)} label={nft ? 'Upload artwork' : 'Upload item image'} /><Field id="listing-name" label="Item name" placeholder="Something your community will love" required maxLength={100} minLength={3} value={form.name} onChange={e => set('name', e.target.value)} /><Field textarea id="listing-description" label="Description" placeholder="Tell the story. Include delivery details and what’s included." required minLength={10} maxLength={3000} value={form.description} onChange={e => set('description', e.target.value)} /><div className="form-row"><Field id="listing-price" label={`Price in $${token.symbol}`} inputMode="decimal" placeholder="100" required value={form.price} onChange={e => set('price', e.target.value)} /><Field id="listing-quantity" label={form.type === 'Create NFT' ? 'Supply' : 'Quantity'} type="number" min="1" max="100000" required value={form.quantity} onChange={e => set('quantity', e.target.value)} /></div><div className="seller-wallet" data-testid="listing-seller-wallet"><ShieldCheck size={15} /><span>Seller wallet</span><code>{short(wallet)}</code></div><ErrorBox error={error} /><Btn type="submit" data-testid="listing-submit" busy={busy} disabled={!form.image || nft}>{nft ? 'NFT services not configured' : 'Publish listing'}<ArrowUpRight size={16} /></Btn></form>;
};

const Checkout = ({ item, token, close, refresh }) => {
  const { provider, wallet, requireWallet } = useWallet(); const [delivery, setDelivery] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [order, setOrder] = useState(null), [sent, setSent] = useState(false), [paid, setPaid] = useState(false);
  async function buy(e) { e.preventDefault(); if (!requireWallet()) return; setBusy(true); setError(''); try {
    const { Transaction } = await import('@solana/web3.js');
    const payment = order || await api('/orders', { method: 'POST', body: { listing_id: item.id, delivery } }); setOrder(payment);
    const tx = Transaction.from(Buffer.from(payment.transaction, 'base64')); const signed = await provider.current.signTransaction(tx);
    await api('/transactions/send', { method: 'POST', body: { kind: 'order', id: payment.id, transaction: Buffer.from(signed.serialize()).toString('base64') } }); setSent(true); toast.info('Payment submitted. Wait for finalization, then check your payment.'); refresh();
  } catch(e) { setError(e.message); } finally { setBusy(false); } }
  async function verify() { setBusy(true); setError(''); try { await api(`/orders/${order.id}/verify`, { method: 'POST' }); setPaid(true); refresh(); toast.success('Payment verified on Solana. Your order is confirmed.'); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <div className="form-stack"><div className="checkout-item"><img src={item.image} alt={item.name} /><div><span className="eyebrow">{item.type}</span><h3 data-testid="checkout-item-name">{item.name}</h3><strong className="green" data-testid="checkout-price">{item.price} ${token.symbol}</strong></div></div><p className="muted" data-testid="checkout-description">{item.description}</p><div className="seller-wallet"><span>Seller</span><code>{short(item.seller)}</code></div>{paid ? <div className="success-box" data-testid="payment-success"><ShieldCheck />Payment finalized. View delivery updates in My Purchases.</div> : sent ? <><p className="info-note" data-testid="payment-pending">Payment submitted. Solana finalization can take a little time. Your order is saved in My Purchases.</p><Btn data-testid="verify-purchase" onClick={verify} busy={busy}>Check payment</Btn></> : <form className="form-stack" onSubmit={buy}><Field textarea id="checkout-delivery" label={item.category === 'Physical' ? 'Delivery name & full shipping address' : 'Delivery contact (email or preferred contact)'} required minLength={5} maxLength={1000} value={delivery} onChange={e => setDelivery(e.target.value)} hint="Only you and the seller can see these details." /><div className="info-note warning"><ShieldCheck size={19} /><p>Pay directly to the seller in ${token.symbol}. Network and token-account fees are paid in SOL. This is not an escrow service; delivery is the seller’s responsibility.</p></div><Btn type="submit" data-testid="confirm-purchase" disabled={wallet === item.seller} busy={busy}>{wallet === item.seller ? 'This is your listing' : `Pay ${item.price} $${token.symbol}`}<ArrowUpRight size={15} /></Btn></form>}<ErrorBox error={error} />{order && !paid && <small className="muted">If you cancel signing, release the reserved item from My Purchases after the transaction expires.</small>}</div>;
};

export default function Market({ token }) {
  const [category, setCategory] = useState('All'), [open, setOpen] = useState(false), [selected, setSelected] = useState(null); const { requireWallet } = useWallet();
  const { data, loading, error, reload } = useData(`/tokens/${token.address}/listings?category=${category}`);
  const add = () => { if (requireWallet()) setOpen(true); };
  return <><div className="section-heading"><div><span className="eyebrow">YOUR COMMUNITY. YOUR CURRENCY.</span><h2 className="display-h2" data-testid="token-market-title">${token.symbol} Market<span className="green">.</span></h2><p>Made by the community. Paid in ${token.symbol}.</p></div><Btn data-testid="add-listing-button" onClick={add}><Plus size={17} />Add Listing</Btn></div><div className="filter-bar"><div className="pills">{['All', 'NFT', 'Artwork', 'Physical'].map(c => <button key={c} data-testid={`market-category-${c.toLowerCase()}`} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c === 'All' ? 'All items' : c}</button>)}</div><span className="muted small-text" data-testid="listing-count">{data?.length || 0} items</span></div>{loading ? <Loading /> : error ? <ErrorBox error={error} /> : data?.length ? <div className="listing-grid">{data.map(item => <button key={item.id} data-testid={`listing-${item.id}`} className="listing-card" onClick={() => setSelected(item)}><div className="listing-img"><img src={item.image} alt={item.name} /><span className="image-chip">{item.type}</span></div><div className="listing-details"><h3>{item.name}</h3><div><strong data-testid={`listing-price-${item.id}`}>{item.price} <span>${token.symbol}</span></strong><span>{item.quantity > 0 ? `${item.quantity} left` : 'Sold out'}</span></div></div></button>)}</div> : <Empty icon={ShoppingBag} title={category === 'NFT' ? 'A new home for your collectibles' : 'Your token. Your first market moment.'} text={category === 'NFT' ? 'NFT listing and minting will be available once storage and atomic exchange services are configured.' : `Be the first to bring art or merchandise to the $${token.symbol} community.`}>{category !== 'NFT' && <Btn data-testid="first-listing-button" onClick={add}><Plus size={16} />Create the first listing</Btn>}</Empty>}<Modal open={open} onClose={() => setOpen(false)} title={`List in $${token.symbol} Market`} description="Turn community creativity into something people can own." id="listing"><ListingForm token={token} close={() => setOpen(false)} refresh={reload} /></Modal><Modal open={!!selected} onClose={() => setSelected(null)} title="Make it yours." description={`This purchase is paid in $${token.symbol}, not SOL or USD.`} id="checkout">{selected && <Checkout item={selected} token={token} close={() => setSelected(null)} refresh={reload} />}</Modal></>;
}