import { TrendingUp, ShieldCheck } from 'lucide-react';
import { useData, short, money } from '../lib/api';
import { External, Loading, ErrorBox, Empty } from '../components/Kit';

export default function Trade({ token, integrated = false }) {
  const { data, loading, error } = useData(`/tokens/${token.address}/transactions`);
  return <><div className="section-heading"><div><span className="eyebrow">PUMP.FUN POWERS THE TRADE. MART BUILDS THE WORLD.</span><h2 className="display-h2" data-testid="trade-title">Trade ${token.symbol}</h2></div><External id="trade-dex-link" href={token.dex_url}>Open chart</External></div>
    {integrated ? <div className="integrated-trade-notice" data-testid="integrated-trade-notice"><p>Buy and sell through the original Pump.fun trading experience. Your wallet signs each transaction. Review network fees, price impact, and slippage before signing.</p><External href={token.pump_url} id="trade-buy" className="btn btn-primary">Trade ${token.symbol}</External></div> : <div className="trade-layout"><div className="chart-panel">{token.pair ? <iframe data-testid="token-price-chart" title={`${token.symbol} market chart`} src={`${token.dex_url}?embed=1&loadChartSettings=0&trades=0&tabs=0&info=0&chartLeftToolbar=0&chartTheme=dark&theme=dark`} allow="clipboard-write" loading="lazy" /> : <Empty icon={TrendingUp} title="Chart not indexed yet" text="Market data will appear when a supported trading pair is indexed by DexScreener." />}<p className="chart-footnote">Live chart provided by DexScreener. If the embedded chart is unavailable, use Open chart.</p></div><aside className="trade-panel"><div className="pump-badge"><span className="pump-pill" />PUMP.FUN</div><h3>Your token.<br />The original trading engine.</h3><p>Buy and sell directly through Pump.fun. Your assets stay in your wallet.</p><div className="trade-price"><span>Reference price</span><strong data-testid="trade-reference-price">{money(token.price)}</strong></div><External id="trade-buy" className="btn btn-primary" href={token.pump_url}>Buy ${token.symbol}</External><External id="trade-sell" className="btn btn-secondary" href={token.pump_url}>Sell ${token.symbol}</External><p className="small-text muted"><ShieldCheck size={14} />Opens Pump.fun. Review fees and slippage before signing.</p></aside></div>}
    <div className="section-heading transactions-heading"><h3>Recent on-chain activity</h3><External id="all-token-transactions" href={token.explorer_url}>View on Solscan</External></div><p className="small-text muted">Recent transactions referencing this mint. Not all activity represents a trade.</p>{loading ? <Loading /> : error ? <ErrorBox error={error} /> : data?.length ? <div className="transaction-table" data-testid="recent-transactions"><div className="transaction-row table-heading"><span>Transaction</span><span>Time</span><span>Status</span><span>Explorer</span></div>{data.map(tx => <div className="transaction-row" data-testid={`transaction-${tx.signature}`} key={tx.signature}><code>{short(tx.signature)}</code><span>{tx.blockTime ? new Date(tx.blockTime * 1000).toLocaleString() : 'Pending'}</span><span className={tx.err ? 'negative' : 'positive'}>{tx.err ? 'Failed' : tx.confirmationStatus}</span><External id={`tx-explorer-${tx.signature}`} href={tx.url}>View</External></div>)}</div> : <Empty title="No recent mint activity" text="Check Solscan for complete transaction history." />}</>;
}